-- Build xvConvert
--   Debug or Release
--   Win32 or Win64

-- Target directory for the build files generated by premake5

-- set default action
if _ACTION == nil then _ACTION = "vs2015" end

newoption {
  trigger     = "builddir",
  value       = "build",
  description = "Directory for the generated build files"
}

BUILDDIR = _OPTIONS["builddir"] or "build"

-- hook for the clean action
if _ACTION == "clean" then
  os.rmdir("bin")
  os.rmdir("build")
  -- os.execute('for /d %d in ('..SRC_DIR..'\\*.tlog) do rd /q /s "%d"')
  -- os.execute('del /Q /S /F /A *Log.htm thumbs.db *bak.def 2> NUL')
  extensions = {
    --[["dll",]] --[["lib",]] "exe",
    "pdb", --[["exp",]] "obj", "manifest",
    "sln", "suo", "sdf", "opensdf",
    "bak", "tmp", "log", "tlog",
  }
  os.execute('@echo off && for %e in ('.. table.concat(extensions," ") ..') do del /Q /S /F /A *.%e 2> NUL')
  -- remove empty directories
  -- http://blogs.msdn.com/b/oldnewthing/archive/2008/04/17/8399914.aspx
  -- os.execute('@echo off && for /f "usebackq" %d in (`"dir /ad/b/s | sort /R"`) do rd "%d" 2> NUL ')
  -- os.exit() -- don NOT exit and let the native premake clean action run
end

workspace "xvConvert"
  configurations { "Debug", "Release" }
  platforms { "Win32", "x64" }
  targetdir "bin/$(Platform)/$(ProjectName)/$(Configuration)"
--  location(BUILDDIR)

  defines {
    "_CRT_SECURE_NO_WARNINGS",
    "_CRT_SECURE_NO_DEPRECATE",
    "_CRT_NONSTDC_NO_DEPRECATE"
  }
 
  filter { "platforms:Win32" }
    system "Windows"
    architecture "x32"

  filter { "platforms:x64" }
    system "Windows"
    architecture "x64"
    targetsuffix "_x64"

  filter { "configurations:Debug" }
    defines {
      "DEBUG", 
      "_DEBUG"
    }
    symbols "On"

  filter { "configurations:Release" }
    defines {
      "NDEBUG"
    }
	optimize "On"

  filter {}

-- xvConvert
project ("xvConvert")
  language "C"
  kind "ConsoleApp"

  files { "src/xvConvert.c"}

  location( BUILDDIR.."/".."xvConvert" )
  targetname "xvConvert"

